apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-env-selected
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "echo SPECIAL_TYPE_KEY=$(SPECIAL_TYPE_KEY)"]
      env:
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: demo
              key: log.verbosity
              optional: true
  restartPolicy: Never
