apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-env-all
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "env"]
      envFrom:
        - configMapRef:
            name: demo
  restartPolicy: Never
