apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-file-all
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "ls -a /etc/secrets"]
      resources: { limits: { cpu: "0.1", memory: "10Mi" } }
      volumeMounts:
        - name: volume-opaque
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: volume-opaque
      secret:
        secretName: secret-opaque
  restartPolicy: Never
