apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-env-all
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "env"]
      resources: { limits: { cpu: "0.1", memory: "10Mi" } }
      envFrom:
        - secretRef:
            name: secret-opaque
  restartPolicy: Never
