apiVersion: v1
kind: Secret
metadata:
  name: secret-registrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-private-reg
spec:
  containers:
    - name: private-reg-container
      image: myimage:1.0
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: secret-registrykey
