apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-file-specific
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "cat /etc/secrets/my-group/my-username"]
      resources: { limits: { cpu: "0.1", memory: "10Mi" } }
      volumeMounts:
        - name: volume-opaque
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: volume-opaque
      secret:
        secretName: secret-opaque
        items:
          - key: username
            path: my-group/my-username
  restartPolicy: Never
