apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-env-specific
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "env"]
      resources: { limits: { cpu: "0.1", memory: "10Mi" } }
      env:
        - name: another_name
          valueFrom:
            secretKeyRef:
              name: secret-opaque
              key: password
  restartPolicy: Never
