apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: probe-readiness-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-readiness-pod
  template:
    metadata:
      labels:
        app: probe-readiness-pod
    spec:
      containers:
        - name: bash
          image: bash
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              trap "echo got TERM; exit" TERM
              while true; do
                t=$(shuf -i 20-30 -n 1)
                touch /tmp/healthy
                echo Healthy for $t seconds
                sleep $t

                t=$(shuf -i 20-30 -n 1)
                rm -f /tmp/healthy
                echo Unhealthy for $t seconds
                sleep $t
              done
          readinessProbe:
            exec:
              command: ["test", "-e", "/tmp/healthy"]
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: probe-readiness-svc
spec:
  selector:
    app: probe-readiness-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
