apiVersion: v1
kind: Pod
metadata:
  name: bash-sleep
  labels:
    maxim/app: infra-test
    test.io/tier: backend
spec:
  containers:
    - name: bash-container
      image: bash
      imagePullPolicy: IfNotPresent
      command: ["sleep", "1d"]
  restartPolicy: OnFailure
