apiVersion: v1
kind: Pod
metadata:
  name: command-once
spec:
  containers:
    - name: busybox-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["printenv", "HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
