apiVersion: v1
kind: Pod
metadata:
  name: command-continuous
spec:
  containers:
    - name: busybox-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
      args:
        - "-c"
        - |-
          while true; do
            date +'%Y.%m.%d %H:%M:%S'
            sleep 10
          done
  restartPolicy: OnFailure
