apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-emptydir
spec:
  volumes:
    - name: logs-volume
      hostPath:
        path: /data/logs # directory location on host
        type: Directory # this field is optional
  containers:
    - image: busybox
      name: busybox
      resources: { limits: { cpu: "0.1", memory: "50Mi" } }
      args:
        - /bin/sh
        - -c
        - |
          tail /logs/time.txt
          for i in $(seq 1 3); do
            date +'%Y.%m.%d %H:%M:%S'
            sleep 5
          done | tee -a /logs/time.txt
      volumeMounts:
        - mountPath: /logs
          name: logs-volume
