apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  # It is nice to have labels for ReplicaSet itself
  # labels:
  #   app: nginx-app
  #   tier: frontend
spec:
  # by default replicas equals 1
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
