apiVersion: v1
kind: Pod
metadata:
  name: busy124
  labels:
    tier: frontend
spec:
  containers:
    - name: busybox
      image: busybox:1.24.0
      imagePullPolicy: IfNotPresent
      args: ["sleep", "1000"]
---
apiVersion: v1
kind: Pod
metadata:
  name: busy132
  labels:
    tier: frontend
spec:
  containers:
    - name: busybox
      imagePullPolicy: IfNotPresent
      image: busybox:1.32.0
      args: ["sleep", "1000"]
